#!/usr/bin/env zsh

# Split the STOW_FOLDERS variable into an array
folders=(${(s:,:)STOW_FOLDERS})

# Loop through each folder and run stow
for folder in $folders; do
    stow -d $DOTFILES -t $HOME $folder
done
