#!/usr/bin/env bash
alias aoeu="setxkbmap us"
alias snth="setxkbmap us"
alias xsc="xclip -selection clipboard"
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"

alias esc="$HOME/.config/sway/config"
alias vim="$VIM"
alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim $VIM"
alias work="cd ~/work"

alias python="python3"
alias cbp="cat $DOTFILES/zsh/.config/.zsh_profile"
alias ebp="$VIM $DOTFILES/.zsh_profile"
alias bp="dotFileInstall && source ~/.zshrc"
alias yolo="git push origin master --force --no-verify"
alias eirc="nvim $XDG_CONFIG_HOME/i3/i3config"
alias cvrc="cat $DOTFILES/vimrc/.vimrc"
alias dotFileInstall="$DOTFILES/install"

alias pjson="python -mjson.tool"
alias killBT="rfkill block bluetooth"
alias unKillBT="rfkill unblock bluetooth"
alias cclip="xclip -selection clipboard"
alias pclip="xclip -selection clipboard"
alias livestream_screenkey="screenkey -s large --scr 2 -p bottom --geometry 1210x300+712+810";
alias yt_screenkey="screenkey -s large --scr 1 -p bottom --geometry 510x300+1412+850";

alias mynpm='rm ~/.npmrc'
